language: objective-c

script: 
- xcodebuild -project BButtonDemo.xcodeproj -target BButtonDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -project BButtonDemo.xcodeproj -target BButtonDemoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

branches:
only:
- master