language: objective-c

script: 
- xctool -project BButtonDemo.xcodeproj -scheme BButtonDemo -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO build
- xctool -project BButtonDemo.xcodeproj -scheme BButtonDemoTests -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO test

branches:
only:
- master