language: objective-c

script: 
- xctool -project BButtonDemo.xcodeproj -scheme BButtonDemo -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO build test
- xctool -project BButtonDemo.xcodeproj -scheme BButtonDemoTests -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO build test

branches:
only:
- master